volumes:
  creator-db-data:

services:
  common:
    container_name: common
    build: ../common
    image: common:1.0.0

  creator-db:
    container_name: creator-db
    image: mariadb:latest
    ports:
      - "3301:3306"
    environment:
      MARIADB_USER: creator
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: creator
      MARIADB_ROOT_PASSWORD: rootpassword
    volumes:
      - creator-db-data:/var/lib/mariadb

  creator:
    container_name: creator
    depends_on:
      - common
      - creator-db
    build: .
    image: creator:1.0.0
    ports:
      - "8001:8001"
    restart: always
    environment:
      spring.datasource.url: jdbc:mariadb://creator-db:3301/creator
      spring.datasource.username: creator
      spring.datasource.password: password
    command: --spring.profiles.active=dev
