version: '3.1'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.8.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  creator-db:
    image: mariadb:10.7.3
    ports:
      - "3306:3306"
    environment:
      MARIADB_USER: creator
      MARIADB_PASSWORD: P!a7WsND98@?5mK
      MYSQL_DATABASE: creator
      MARIADB_ROOT_PASSWORD: M78$69KrP7o^aG7

  common:
    build: ../common
    image: common:1.0.0

  creator:
    depends_on:
      - common
      - creator-db
      - kafka
    build: .
    image: creator:1.0.0
    ports:
      - "8001:8001"
    restart: always
    environment:
      spring.datasource.url: jdbc:mariadb://creator-db:3306/creator
      spring.datasource.username: creator
      spring.datasource.password: P!a7WsND98@?5mK

      spring.kafka.bootstrap-servers: kafka:9092
    command: --spring.profiles.active=dev
